<?php
/**
 * DimensionType
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  SellingPartnerApi
 *
 * @license BSD-3-Clause
 * Modified by __root__ on 07-January-2025 using {@see https://github.com/BrianHenryIE/strauss}.
 */

/**
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0;
use ArrayAccess;
use WPLab\Amazon\SellingPartnerApi\Model\BaseModel;
use WPLab\Amazon\SellingPartnerApi\Model\ModelInterface;

/**
 * DimensionType Class Doc Comment
 *
 * @category Class
 * @description The dimension type attribute of an item.
 * @package  SellingPartnerApi
 * @group 
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class DimensionType extends BaseModel implements ModelInterface, ArrayAccess, \JsonSerializable, \IteratorAggregate
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DimensionType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'height' => '\WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits',
        'length' => '\WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits',
        'width' => '\WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits',
        'weight' => '\WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'height' => null,
        'length' => null,
        'width' => null,
        'weight' => null
    ];



    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'height' => 'Height',
        'length' => 'Length',
        'width' => 'Width',
        'weight' => 'Weight'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'height' => 'setHeight',
        'length' => 'setLength',
        'width' => 'setWidth',
        'weight' => 'setWeight'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'height' => 'getHeight',
        'length' => 'getLength',
        'width' => 'getWidth',
        'weight' => 'getWeight'
    ];


    
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['height'] = $data['height'] ?? null;
        $this->container['length'] = $data['length'] ?? null;
        $this->container['width'] = $data['width'] ?? null;
        $this->container['weight'] = $data['weight'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];
        return $invalidProperties;
    }


    /**
     * Gets height
     *
     * @return \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null $height height
     *
     * @return self
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }
    /**
     * Gets length
     *
     * @return \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null $length length
     *
     * @return self
     */
    public function setLength($length)
    {
        $this->container['length'] = $length;

        return $this;
    }
    /**
     * Gets width
     *
     * @return \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null $width width
     *
     * @return self
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }
    /**
     * Gets weight
     *
     * @return \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param \WPLab\Amazon\SellingPartnerApi\Model\CatalogItemsV0\DecimalWithUnits|null $weight weight
     *
     * @return self
     */
    public function setWeight($weight)
    {
        $this->container['weight'] = $weight;

        return $this;
    }
}


