<?php

defined( 'ABSPATH' ) || exit;

// Auto generated by wpfluent Installer.

return array(
    'name'           => 'Fluent Booking Pro',
    'slug'           => 'fluent-booking',
    'domain_path'    => '/language',
    'text_domain'    => 'fluent-booking',
    'hook_prefix'    => 'fluent-booking/',
    'rest_namespace' => defined('FCAL_API_NAMESPACE') ? FCAL_API_NAMESPACE : 'fluent-booking',
    'rest_version'   => 'v2',
    'env'            => 'production',
    'cipher'         => 'AES-256-CBC',
);
